[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[functions]
  node_bundler = "esbuild"

[[functions]]
  path = "/get-org-analytics"
  timeout = 26

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
